"""Run lifecycle: trigger, history, and live streaming over WebSocket."""

from __future__ import annotations

import asyncio
import uuid

from fastapi import APIRouter, HTTPException, Query, Request, WebSocket, WebSocketDisconnect
from pydantic import BaseModel

from ..core.config import settings
from ..core.security import (
    enforce_budget, enforce_rate_limit, gating_enabled, is_admin,
)
from ..db.schema import Run, WorkflowConfig
from ..db.store import store
from ..orchestration import Orchestrator
from ..ws import broker

router = APIRouter(prefix="/api/runs", tags=["runs"])
orchestrator = Orchestrator()


def _as_demo(workflow: WorkflowConfig) -> WorkflowConfig:
    """Return a copy of the workflow with every agent forced onto the demo model.

    This is what makes the deployment safe to share: an anonymous visitor still
    gets the entire experience — live streaming, the tool-calling loop, parallel
    stages, conditional skips, the full trace — but every token is generated by
    the built-in mock provider, so a public run can never bill you.

    Deep-copied so the stored workflow is never mutated. `fallback_model` is
    cleared too: leaving it pointed at a billed provider would reintroduce the
    very cost this prevents if the demo provider ever failed.
    """
    demo = workflow.model_copy(deep=True)
    for agent in demo.agents:
        agent.model_provider = settings.demo_provider
        agent.model_name = settings.demo_model
        agent.fallback_model = None
    return demo

# asyncio only holds a weak reference to a bare create_task(...), so a run can be
# garbage-collected before it finishes. Keep a strong ref until the task is done.
_background_runs: set[asyncio.Task] = set()


def _spawn_run(workflow, run_input: str, run_id: str, trigger_source: str) -> None:
    task = asyncio.create_task(
        orchestrator.run_workflow(
            workflow,
            run_input,
            run_id=run_id,
            trigger_source=trigger_source,
            emit=broker.emitter(run_id),
        )
    )
    _background_runs.add(task)
    task.add_done_callback(_background_runs.discard)


class TriggerRequest(BaseModel):
    workflow_id: str
    input: str = ""


class TriggerResponse(BaseModel):
    run_id: str


def start_run(
    workflow_id: str,
    run_input: str,
    trigger_source: str,
    *,
    force_demo: bool = False,
) -> str:
    """Create the background run task and return its id (call from the loop).

    Shared by the manual trigger, webhooks, and the scheduler. The daily spend
    cap is enforced here rather than at each call site, so EVERY path into a run
    — including scheduled and webhook triggers — is covered by one check.
    """
    workflow = store.get_workflow(workflow_id)
    if workflow is None:
        raise HTTPException(status_code=404, detail="Workflow not found")
    if force_demo:
        workflow = _as_demo(workflow)
    else:
        # A demo run costs nothing, so it's never blocked by the spend cap.
        enforce_budget()
    run_id = uuid.uuid4().hex
    _spawn_run(workflow, run_input, run_id, trigger_source)
    return run_id


@router.post("/trigger", response_model=TriggerResponse)
async def trigger_run(req: TriggerRequest, request: Request) -> TriggerResponse:
    """Start a run in the background. Subscribe to /api/runs/ws/{run_id} to watch.

    Open to anyone — but a non-admin caller's run is forced onto the demo model.
    """
    enforce_rate_limit(request)
    admin = is_admin(request.headers.get("x-admin-token"))
    run_id = start_run(
        req.workflow_id, req.input, "manual",
        force_demo=gating_enabled() and not admin,
    )
    return TriggerResponse(run_id=run_id)


@router.get("", response_model=list[Run])
def list_runs(
    workflow_id: str | None = None,
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
) -> list[Run]:
    """Most recent runs first. Paginated so history stays bounded as runs pile up."""
    return store.list_runs(workflow_id, limit=limit, offset=offset)


@router.get("/{run_id}", response_model=Run)
def get_run(run_id: str) -> Run:
    run = store.get_run(run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="Run not found")
    return run


@router.websocket("/ws/{run_id}")
async def stream_run(websocket: WebSocket, run_id: str) -> None:
    """Stream live events for a run that was started via /trigger."""
    await websocket.accept()
    try:
        async for event in broker.subscribe(run_id):
            await websocket.send_json(event)
    except WebSocketDisconnect:
        pass


@router.websocket("/ws")
async def start_and_stream(websocket: WebSocket) -> None:
    """Start a run AND stream it over a single socket — the live-demo path.

    Client sends {"workflow_id": "...", "input": "..."} then receives the full
    event stream (run_started → tokens → run_completed).
    """
    await websocket.accept()
    try:
        req = await websocket.receive_json()
        workflow = store.get_workflow(req.get("workflow_id", ""))
        if workflow is None:
            await websocket.send_json({"type": "error", "message": "Workflow not found"})
            await websocket.close()
            return

        # A browser can't set custom headers on a WebSocket handshake, so the
        # admin token travels in this first message instead of X-Admin-Token.
        admin = is_admin(req.get("admin_token"))
        force_demo = gating_enabled() and not admin

        # The socket is already accepted, so guard failures have to be reported
        # as an error frame rather than an HTTP status.
        try:
            enforce_rate_limit(websocket)
            if not force_demo:
                enforce_budget()
        except HTTPException as exc:
            await websocket.send_json({"type": "error", "message": exc.detail})
            await websocket.close()
            return

        if force_demo:
            workflow = _as_demo(workflow)
        run_id = uuid.uuid4().hex
        _spawn_run(workflow, req.get("input", ""), run_id, "manual")
        async for event in broker.subscribe(run_id):
            await websocket.send_json(event)
    except WebSocketDisconnect:
        pass
